ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER PROJECT1 IDENTIFIED BY PROJECT1;

GRANT RESOURCE, CONNECT TO PROJECT1;

ALTER USER PROJECT1 DEFAULT TABLESPACE 
SYSTEM QUOTA UNLIMITED ON SYSTEM;